### ISSUE TITLE
No such file or directory: '***/omniglot/vinyals_train_labels.json'

### ISSUE THREAD

**Issue by Yxt1212** [alinlab/PsCo#1]
Hi，thanks for your great work!
When i run your code , I meet a problem:"No such file or directory: '***/omniglot/vinyals_train_labels.json'.But I can't find this file.And could you please share the link of downloading miniimagenet and other cross domain dataset? 
Thanks a lot!

**Comment by huiwon-jang** [comment]
Hi, thank you for your interest.

I've updated `/splits` to contain `vinyals_{train, val, test}_labels.json` now. You can find the files in `/splits/omniglot`.

And I changed **README install** to have the links of the datasets.
