### ISSUE TITLE
What is vinyals?

### ISSUE THREAD

**Issue by MyJumperBroke23** [alinlab/PsCo#3]
Trying to train using the omniglot dataset right now, getting an error because I can't find vinyals_x_.json as specified in 

```
        with open(os.path.join(self.root, f'vinyals_{self.split}_labels.json'), mode='r') as f:
            dir_list = json.load(f)
```

What is this supposed to be?

**Comment by huiwon-jang** [comment]
Hi, the json files for train, valid, and test are located in `./splits/omniglot`.
